#!/bin/bash

# usage: ./pomodoro-timer 30m "Take a break!" "sound.mp3"

#cmd="go run elapsed.go"
#cmd="./elapsed"
cmd="elapsed"

duration="$1"
msg="$2"
sound="$3"
title="$4"
player="$5"

[ -n "$duration" ] || duration="30m"
[ -n "$msg" ] || msg="Timer expired"
[ -n "$sound" ] || sound="$HOME/sounds/break.mp3"
#[ -n "$sound" ] || sound="/usr/share/sounds/freedesktop/stereo/complete.oga"
#[ -n "$sound" ] || sound="$HOME/sounds/break-2.mp3"
[ -n "$title" ] || title="Pomodoro timer"
[ -n "$player" ] || player="mplayer"
#[ -n "$player" ] || player="paplay"

watch -n 10 -bcet "$cmd -t \"$title\" $($cmd $duration) || (notify-send \"$msg\" && $player \"$sound\" > /dev/null 2>&1 & false)"

