#!/bin/bash

# show time spent on tasks by period

# $1 - path to elapsed.log
# $2 - "days" for days interval, months by default

tf="%Y-%m"

if [ "$2" = "days" ]; then
    tf="%Y-%m-%d"
fi

query="select title, strftime(\"$tf\", start) \"period\", \
    replace(strftime('%j days %H:%M:%S', sum(\"diff(sec)\"), 'unixepoch', '-1 day'), '365', '000') \"duration\", \
    printf(\"%.2f\", sum(\"diff(sec)\")/3600.0)  \"hours\" \
    from elapsed \
    group by title, strftime(\"$tf\", start)"

csvsql --query "$query" "$1" | csvlook
